title: Demo Catalogue
email: john@emailaddress.hore
description: >- # this means to ignore newlines until "baseurl:"
  A prototype of a personal catalogue.
url: "jdbann.github.io/catalogue"
baseurl: "/catalogue"
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
